version: 2
executorType: docker
containerInfo:
  - image: markfirmware/ultibo-docker2-x64-1.3.245-rc3
stages:
  build:
    workDir: ~/ultibo-slideshow
    steps:
      - type: checkout
      - name: Build and test
        type: shell
        command: ./build.sh
      - name: List files
        type: shell
        command: ls -ltR
      - name: Save artifacts
        type: artifacts-store
        path: build-output
        destination: ultibo-slideshow
