version: 2
executorType: docker
containerInfo:
# - image: markfirmware/ultibo-docker2-x64-1.3.245-rc3@sha256:0f8ca2f9d375b570d30afb4b2cdea88e711e27abbc00edc04b217d309f084961
  - image: markfirmware/ultibo-docker2-x64-1.3.245-dbg-rc1@sha256:a4649b9dd6d08a8d0cf917941f96c656b8f8245f045c699634c434fd9e832612
stages:
  build:
    workDir: ~/ultibo-slideshow
    steps:
      - type: checkout
      - name: Build and test
        type: shell
        command: ./build.sh
      - name: List files
        type: shell
        command: ls -ltR
      - name: Save artifacts
        type: artifacts-store
        path: build-output
        destination: ultibo-slideshow
